-- 掌上律师 MVP - H2 数据库初始化脚本
-- 注意：H2 兼容 PostgreSQL 模式，但向量扩展需要特殊处理

-- ========== 用户表 ==========
CREATE TABLE IF NOT EXISTS app_user (
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    openid         VARCHAR(64) UNIQUE NOT NULL,
    nickname       VARCHAR(128),
    avatar_url     VARCHAR(512),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========== 案件档案表 ==========
CREATE TABLE IF NOT EXISTS case_profile (
    case_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL,
    domain_type    VARCHAR(32) NOT NULL DEFAULT 'LABOR',
    status         VARCHAR(32) NOT NULL DEFAULT 'COLLECTING',
    title          VARCHAR(256),
    facts_json     CLOB NOT NULL DEFAULT '{}',
    issues_json    CLOB NOT NULL DEFAULT '[]',
    laws_json      CLOB NOT NULL DEFAULT '[]',
    timeline_json  CLOB NOT NULL DEFAULT '[]',
    evidence_refs  CLOB NOT NULL DEFAULT '[]',
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========== 对话会话表 ==========
CREATE TABLE IF NOT EXISTS chat_session (
    session_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id        BIGINT,
    user_id        BIGINT NOT NULL,
    summary        VARCHAR(512),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========== 对话消息表 ==========
CREATE TABLE IF NOT EXISTS chat_message (
    message_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id     BIGINT NOT NULL,
    role           VARCHAR(16) NOT NULL,
    content        CLOB NOT NULL,
    evidence_refs  CLOB,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========== 法律之星查询缓存表 ==========
CREATE TABLE IF NOT EXISTS law_cache (
    cache_key      VARCHAR(128) PRIMARY KEY,
    source         VARCHAR(32) NOT NULL,
    response_json  CLOB NOT NULL,
    expires_at     TIMESTAMP NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========== 向量知识库表（H2 简化版，不使用向量扩展） ==========
CREATE TABLE IF NOT EXISTS domain_knowledge_vector (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_type    VARCHAR(32) NOT NULL,
    content_type   VARCHAR(32) NOT NULL,
    content_id     VARCHAR(64) NOT NULL,
    text_chunk     CLOB NOT NULL,
    -- H2 不支持 pgvector，暂时存储为文本，生产环境迁移到 PostgreSQL
    embedding_text CLOB,
    metadata_json  CLOB DEFAULT '{}',
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========== 时间轴事件表（独立表，替代 case_profile.timeline_json 整条读写） ==========
CREATE TABLE IF NOT EXISTS timeline_event (
    event_id       VARCHAR(36) PRIMARY KEY,
    case_id        BIGINT NOT NULL,
    event_time     VARCHAR(32),
    description    CLOB,
    type           VARCHAR(32) DEFAULT 'USER_ACTION',
    is_deadline    BOOLEAN DEFAULT FALSE,
    reminder_text  VARCHAR(512),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_tle_case ON timeline_event(case_id);

-- ========== 索引 ==========
CREATE INDEX IF NOT EXISTS idx_case_user ON case_profile(user_id);
CREATE INDEX IF NOT EXISTS idx_case_domain ON case_profile(domain_type);
CREATE INDEX IF NOT EXISTS idx_case_status ON case_profile(status);
CREATE INDEX IF NOT EXISTS idx_session_case ON chat_session(case_id);
CREATE INDEX IF NOT EXISTS idx_session_user ON chat_session(user_id);
CREATE INDEX IF NOT EXISTS idx_message_session ON chat_message(session_id);
CREATE INDEX IF NOT EXISTS idx_law_cache_expires ON law_cache(expires_at);
CREATE INDEX IF NOT EXISTS idx_dkv_domain ON domain_knowledge_vector(domain_type);
CREATE INDEX IF NOT EXISTS idx_dkv_content_type ON domain_knowledge_vector(content_type);

-- ========== 注释说明 ==========
-- H2 数据库说明：
-- 1. 使用 MODE=PostgreSQL 兼容 PostgreSQL 语法
-- 2. CLOB 类型用于存储大文本（JSON 数据）
-- 3. 向量扩展在 H2 中不可用，生产环境需迁移到 PostgreSQL + pgvector
-- 4. 切换到 PostgreSQL 时，取消注释 application.yml 中的 PostgreSQL 配置
-- 5. PostgreSQL 需要执行 backend/db/init.sql（包含 pgvector 扩展）